{
  "formatVersion": "1.1",
  "component": {
    "group": "com.firebaseui",
    "module": "firebase-ui-database",
    "version": "7.1.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "6.8.3",
      "buildId": "yc3wlm55tfb3vl7oijb2bw6sea"
    }
  },
  "variants": [
    {
      "name": "releaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "com.firebaseui",
          "module": "firebase-ui-common",
          "version": {
            "requires": "7.1.1"
          }
        },
        {
          "group": "com.google.firebase",
          "module": "firebase-database"
        },
        {
          "group": "androidx.legacy",
          "module": "legacy-support-v4",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.recyclerview",
          "module": "recyclerview",
          "version": {
            "requires": "1.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "firebase-ui-database-7.1.1.aar",
          "url": "firebase-ui-database-7.1.1.aar",
          "size": 47419,
          "sha512": "165ce40b1f0382108d20c0f7a8e7706522edbaa16bbaec7b1312eb4eb69b7a849d4f1649c4b739ef9cf80334e6386a9e19560a037f9369195c88d56de62fa3da",
          "sha256": "d3b7f9541f3a1f8642082de41bcba4a1b31e55aea2321323e8027460bf3b19f9",
          "sha1": "56d669023ea09c58a2f1936fcb4ac5eaa7cdd80a",
          "md5": "25200dbf6c2efe41bcc496662c3b05d7"
        }
      ]
    },
    {
      "name": "releaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "com.google.firebase",
          "module": "firebase-bom",
          "version": {
            "requires": "26.0.0"
          },
          "attributes": {
            "org.gradle.category": "platform"
          },
          "endorseStrictVersions": true
        },
        {
          "group": "com.firebaseui",
          "module": "firebase-ui-common",
          "version": {
            "requires": "7.1.1"
          }
        },
        {
          "group": "com.google.firebase",
          "module": "firebase-database"
        },
        {
          "group": "androidx.legacy",
          "module": "legacy-support-v4",
          "version": {
            "requires": "1.0.0"
          }
        },
        {
          "group": "androidx.recyclerview",
          "module": "recyclerview",
          "version": {
            "requires": "1.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "firebase-ui-database-7.1.1.aar",
          "url": "firebase-ui-database-7.1.1.aar",
          "size": 47419,
          "sha512": "165ce40b1f0382108d20c0f7a8e7706522edbaa16bbaec7b1312eb4eb69b7a849d4f1649c4b739ef9cf80334e6386a9e19560a037f9369195c88d56de62fa3da",
          "sha256": "d3b7f9541f3a1f8642082de41bcba4a1b31e55aea2321323e8027460bf3b19f9",
          "sha1": "56d669023ea09c58a2f1936fcb4ac5eaa7cdd80a",
          "md5": "25200dbf6c2efe41bcc496662c3b05d7"
        }
      ]
    }
  ]
}
